swagger: "2.0"

info:
  description: "本ドキュメントでは一般社団法人ソーシャルアクション機構が運営するサービス「福祉Mover」の API サーバの API 仕様を記述する。"
  version: "1.0.0"
  title: "ソーシャルアクション機構 福祉Mover API Documents"
  termsOfService: "https://socialaction.net/mover/user-3/"
  contact:
    url: "https://socialaction.net/mover/user-3/"
  license:
    name: "一般社団法人ソーシャルアクション機構に帰属"
    url: "https://socialaction.net"

host: "localhost:5000"

basePath: "/"

tags:
  - name: "bindata-api"
    description: "bindata-api API"
  - name: "nowpos-api"
    description: "nowpos-api API"
  - name:  "possavs-api"
    description: "possavs/data"
schemes:
  - "http"
paths:
  /nowpos/data:
    get:
      tags:
        - "nowpos-api"
      summary: "全データを取得する。"
      description: "全データを取得する。"
      responses:
        "200":
          description: "全データ"
          schema:
            type: "object"
        "401":
          description: "認証不可"
      security:
        - tokenAuth: []
  /nowpos/data/{id}:
    get:
      tags:
        - "nowpos-api"
      summary: "指定した id の情報を取得する。"
      description: "全データを取得する。"
      parameters:
        - in: "path"
          name: "id"
          description: "データの ID"
          required: true
          type: integer
      responses:
        "200":
          description: "全データ"
        "401":
          description: "認証不可"
      security:
        - basicAuth: []


securityDefinitions:
  basicAuth:
    type: "basic"
  tokenAuth:
    name: "Authorization"
    type: "apiKey"
    in: "header"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
